# parameter for quorum state
UserParameter=proxmox.quorum.status,sudo /usr/sbin/ha-manager status 2>/dev/null | grep -q "quorum OK" && echo 1 || echo 0

# parameter for LVM-usage
UserParameter=pve.storage.total.gb[*],sudo pvesm status --storage $1 | awk 'NR==2 {print $$4/1000/1000}'
UserParameter=pve.storage.used.gb[*],sudo pvesm status --storage $1 | awk 'NR==2 {print $$5/1000/1000}'
UserParameter=pve.storage.pused[*],sudo pvesm status --storage $1 | awk 'NR==2 {print $$7}' | tr -d '%'
UserParameter=pve.storage.discovery,sudo pvesm status | awk 'NR>1 {print $1}'

# parameter for service state
UserParameter=pve.service.state[*],/usr/bin/systemctl is-active --quiet $1 && echo 1 || echo 0